modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="irisflw"
version="${version}"
displayName="Iris Flywheel Compat"
logoFile="icon.png"
authors="Leon"
description='''
Allow Flywheel instancing optimization to be enabled when using iris.
'''
[[dependencies.irisflw]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.irisflw]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="CLIENT"

[[dependencies.irisflw]]
modId="oculus"
mandatory=true
versionRange="[1.6.15,)"
ordering="NONE"
side="CLIENT"

[[dependencies.irisflw]]
modId="flywheel"
mandatory=true
versionRange="[0.6.9,)"
ordering="AFTER"
side="CLIENT"
