modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="irisflw"
version="${version}"
displayName="Oculus Flywheel Compat"
logoFile="icon.png"
authors="Leon"
description='''
Allow Flywheel instancing optimization to be enabled when using iris.
'''
#logoFile = ""

[[dependencies.irisflw]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.irisflw]]
modId = "minecraft"
mandatory=true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.irisflw]]
modId="oculus"
mandatory=true
versionRange="[1.7.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.irisflw]]
modId="flywheel"
mandatory=true
versionRange="[1.0.0,)"
ordering="AFTER"
side="CLIENT"
